networks:
  otel:
    name: otel
    driver: bridge
services:
  otel:
    container_name: otel
    image: otel/opentelemetry-collector:latest
    depends_on:
      - seq
      - aspire
      - jaeger
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - otel
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    extra_hosts:
      - host.docker.internal:host-gateway
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    networks:
      - otel
    volumes:
      - seq_data:/data
    ports:
      - "5341:80"

  aspire:
    container_name: aspire
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPNETCORE__URLS: http://+:18888
      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DOTNET_DASHBOARD__OTLP__AUTHMODE: ApiKey
      DOTNET_DASHBOARD__OTLP__ENDPOINT__URL: http://+:18889
      DOTNET_DASHBOARD__OTLP__HTTP__ENDPOINT__URL: http://+:18890
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
      DASHBOARD__OTLP__PRIMARYAPIKEY: "${ASPIRE_API_KEY:-<<aspire-secret-api-key>>}"
    networks:
      - otel
    ports:
      - "18888:18888"

  # jaeger:
  #   image: jaegertracing/all-in-one:1.22
  #   container_name: jaeger
  #   networks:
  #     - otel
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "14250:14250"
  #     - "9411:9411"

volumes:
    seq_data:
