networks:
  otel:
    name: otel
    driver: bridge
services:
  otel:
    container_name: otel
    image: otel/opentelemetry-collector:latest
    depends_on:
      - seq
      - aspire
    environment:
      - OTEL_LOG_LEVEL=debug
    command: --config=/etc/otel-collector-config.yml
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - otel
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    extra_hosts:
      - host.docker.internal:host-gateway
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    networks:
      - otel
    volumes:
      - seq_data:/data
    ports:
      - "5341:80"

  aspire:
    container_name: aspire
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPNETCORE__URLS: http://+:18888
      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DOTNET_DASHBOARD__OTLP__AUTHMODE: ApiKey
      DOTNET_DASHBOARD__OTLP__ENDPOINT__URL: http://+:18889
      DOTNET_DASHBOARD__OTLP__HTTP__ENDPOINT__URL: http://+:18890
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
      DASHBOARD__OTLP__PRIMARYAPIKEY: "${ASPIRE_API_KEY:-<<aspire-secret-api-key>>}"
    networks:
      - otel
    ports:
      - "18888:18888"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - otel
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
      - "9095:9095"
    environment:
      - ALLOW_STRUCTURED_METADATA=true
    networks:
      - otel
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./tempo-config.yaml:/etc/tempo-config.yaml
      - ./tempo-data:/tmp/tempo
    command: [ "-config.file=/etc/tempo-config.yaml" ]
    ports:
      - "3200:3200"  # grafana API
      - "4319:4317"  # OTLP gRPC
      - "4320:4318"  # OTLP HTTP
      - "9411:9411"  # Zipkin API
    networks:
      - otel
volumes:
    seq_data:
    prom_data:
