receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  otlphttp:
    endpoint: http://seq/ingest/otlp
    tls:
      insecure: true
    
  otlp:
    endpoint: aspire:18889
    tls:
      insecure: true
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
      
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:
     endpoint: otel:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlphttp, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlphttp/logs]