receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlphttp:
    endpoint: http://seq/ingest/otlp
    tls:
      insecure: true
    headers:
      x-otlp-api-key: "b2KEjSeyIwCaEHlBM1Gj"
  otlp:
    endpoint: aspire:18889
    tls:
      insecure: true
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
      #x-otlp-api-key: u81jrTSJLOI269CIBoEC3Mk9XGuByLM9c8bsPUDxKMbRPNOUZeA7lCaImsGC3qoqAc9cf0TFdJamjuJ3ZMBhr8G1p4KaEq6LkSw7K209WZSgDk67KOKYNHwZQtARSN7i

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlphttp]