server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo

compactor:
  compaction:
    compacted_block_retention: 24h

metrics_generator:
  registry:
    external_labels:
      source: tempo
